title: Java PathFinder Documentation
description: JPF is an extensible software model checking framework for Java bytecode programs
baseurl: "/jpf-core"
url: "https://mahmoud-khawaja.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links

markdown: kramdown
highlighter: rouge

relative_links:
  enabled: true
  collections: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - _includes/add_navigation.sh
  - _includes/fix_links.sh

github_username: javapathfinder
